/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Whether `cost_usd` came from provider billing data (authoritative) or catalog price estimation (estimated).
 */

export const CostSource = {
    AUTHORITATIVE: 'authoritative',
    ESTIMATED: 'estimated'
} as const;

export type CostSource = typeof CostSource[keyof typeof CostSource];
