/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PairTarget } from './pair-target';

export interface PairTranscriptSystemMessage {
    'kind': PairTranscriptSystemMessageKindEnum;
    'seq': number;
    'event_id': string;
    'ts': string;
    /**
     * Durable run pair identifier.
     */
    'pair_id': string;
    'target': PairTarget;
    'system_message_kind': PairTranscriptSystemMessageSystemMessageKindEnum;
    'text': string;
}

export const PairTranscriptSystemMessageKindEnum = {
    SYSTEM_MESSAGE: 'system_message'
} as const;

export type PairTranscriptSystemMessageKindEnum = typeof PairTranscriptSystemMessageKindEnum[keyof typeof PairTranscriptSystemMessageKindEnum];
export const PairTranscriptSystemMessageSystemMessageKindEnum = {
    HUMAN_JOINED: 'human_joined',
    HUMAN_LEFT: 'human_left'
} as const;

export type PairTranscriptSystemMessageSystemMessageKindEnum = typeof PairTranscriptSystemMessageSystemMessageKindEnum[keyof typeof PairTranscriptSystemMessageSystemMessageKindEnum];
