/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PairTarget {
    'stage_id': string;
    'node_id': string;
    'node_label': string;
    'visit': number;
    'agent_session_id': string;
    'provider'?: string;
    'model'?: string;
}
