/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PairTarget } from './pair-target';
// May contain unused imports in some cases
// @ts-ignore
import type { PairTranscriptAssistantMessage } from './pair-transcript-assistant-message';
// May contain unused imports in some cases
// @ts-ignore
import type { PairTranscriptAssistantMessageModel } from './pair-transcript-assistant-message-model';
// May contain unused imports in some cases
// @ts-ignore
import type { PairTranscriptDetailRef } from './pair-transcript-detail-ref';
// May contain unused imports in some cases
// @ts-ignore
import type { PairTranscriptError } from './pair-transcript-error';
// May contain unused imports in some cases
// @ts-ignore
import type { PairTranscriptSystemMessage } from './pair-transcript-system-message';
// May contain unused imports in some cases
// @ts-ignore
import type { PairTranscriptToolCall } from './pair-transcript-tool-call';
// May contain unused imports in some cases
// @ts-ignore
import type { PairTranscriptUserMessage } from './pair-transcript-user-message';
// May contain unused imports in some cases
// @ts-ignore
import type { PairTranscriptWarning } from './pair-transcript-warning';

/**
 * @type PairTranscriptEntry
 */
export type PairTranscriptEntry = PairTranscriptAssistantMessage | PairTranscriptError | PairTranscriptSystemMessage | PairTranscriptToolCall | PairTranscriptUserMessage | PairTranscriptWarning;
