/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PairTarget } from './pair-target';
// May contain unused imports in some cases
// @ts-ignore
import type { PairTranscriptDetailRef } from './pair-transcript-detail-ref';

export interface PairTranscriptToolCall {
    'kind': PairTranscriptToolCallKindEnum;
    'seq': number;
    'event_id': string;
    'ts': string;
    /**
     * Durable run pair identifier.
     */
    'pair_id': string;
    'target': PairTarget;
    'tool_call_id': string;
    'tool_name': string;
    'status': PairTranscriptToolCallStatusEnum;
    'summary': string;
    'is_error': boolean;
    'truncated': boolean;
    'detail_ref': PairTranscriptDetailRef;
}

export const PairTranscriptToolCallKindEnum = {
    TOOL_CALL: 'tool_call'
} as const;

export type PairTranscriptToolCallKindEnum = typeof PairTranscriptToolCallKindEnum[keyof typeof PairTranscriptToolCallKindEnum];
export const PairTranscriptToolCallStatusEnum = {
    STARTED: 'started',
    COMPLETED: 'completed'
} as const;

export type PairTranscriptToolCallStatusEnum = typeof PairTranscriptToolCallStatusEnum[keyof typeof PairTranscriptToolCallStatusEnum];
