/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PairTarget } from './pair-target';
// May contain unused imports in some cases
// @ts-ignore
import type { PairTranscriptAssistantMessageModel } from './pair-transcript-assistant-message-model';

export interface PairTranscriptAssistantMessage {
    'kind': PairTranscriptAssistantMessageKindEnum;
    'seq': number;
    'event_id': string;
    'ts': string;
    /**
     * Durable run pair identifier.
     */
    'pair_id': string;
    'target': PairTarget;
    'text': string;
    'model': PairTranscriptAssistantMessageModel;
    'tool_call_count': number;
}

export const PairTranscriptAssistantMessageKindEnum = {
    ASSISTANT_MESSAGE: 'assistant_message'
} as const;

export type PairTranscriptAssistantMessageKindEnum = typeof PairTranscriptAssistantMessageKindEnum[keyof typeof PairTranscriptAssistantMessageKindEnum];
