/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PairTarget } from './pair-target';

export interface PairTranscriptUserMessage {
    'kind': PairTranscriptUserMessageKindEnum;
    'seq': number;
    'event_id': string;
    'ts': string;
    /**
     * Durable run pair identifier.
     */
    'pair_id': string;
    'target': PairTarget;
    /**
     * Durable pair message identifier.
     */
    'message_id': string;
    'client_message_id'?: string | null;
    'text': string;
}

export const PairTranscriptUserMessageKindEnum = {
    USER_MESSAGE: 'user_message'
} as const;

export type PairTranscriptUserMessageKindEnum = typeof PairTranscriptUserMessageKindEnum[keyof typeof PairTranscriptUserMessageKindEnum];
