/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PairStatus } from './pair-status';
// May contain unused imports in some cases
// @ts-ignore
import type { PairTarget } from './pair-target';

export interface PairRecord {
    /**
     * Durable run pair identifier.
     */
    'pair_id': string;
    'run_id': string;
    'status': PairStatus;
    'started_at': string;
    'ended_at'?: string | null;
    'failure_reason'?: string | null;
    'target': PairTarget;
}
