/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PairTargetSelector } from './pair-target-selector';

export interface PairMessageRecord {
    /**
     * Durable pair message identifier.
     */
    'message_id': string;
    'client_message_id'?: string | null;
    /**
     * Durable run pair identifier.
     */
    'pair_id': string;
    'run_id': string;
    'target': PairTargetSelector;
    'text': string;
    'accepted_at': string;
}
