/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthMethod } from './auth-method';
// May contain unused imports in some cases
// @ts-ignore
import type { IdpIdentity } from './idp-identity';

export interface PrincipalUser {
    'kind': PrincipalUserKindEnum;
    'identity': IdpIdentity;
    'login': string;
    'auth_method': AuthMethod;
    'avatar_url'?: string | null;
}

export const PrincipalUserKindEnum = {
    USER: 'user'
} as const;

export type PrincipalUserKindEnum = typeof PrincipalUserKindEnum[keyof typeof PrincipalUserKindEnum];


