/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxProviderKind } from './sandbox-provider-kind';

/**
 * Requested sandbox provider and base image/snapshot from run settings.
 */
export interface RunSandboxPlan {
    'provider': SandboxProviderKind;
    'image'?: string | null;
    'snapshot'?: string | null;
}
