/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunSandboxFailure } from './run-sandbox-failure';
// May contain unused imports in some cases
// @ts-ignore
import type { RunSandboxInstance } from './run-sandbox-instance';
// May contain unused imports in some cases
// @ts-ignore
import type { RunSandboxKind } from './run-sandbox-kind';
// May contain unused imports in some cases
// @ts-ignore
import type { RunSandboxPlan } from './run-sandbox-plan';

/**
 * Sandbox lifecycle record for a run. A run can have a requested sandbox plan before it has an initialized sandbox instance.
 */
export interface RunSandbox {
    'kind': RunSandboxKind;
    'plan': RunSandboxPlan;
    'instance'?: RunSandboxInstance | null;
    'failure'?: RunSandboxFailure | null;
}
