/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Lifecycle state for a run sandbox request.
 */

export const RunSandboxKind = {
    PLANNED: 'planned',
    INITIALIZING: 'initializing',
    READY: 'ready',
    FAILED: 'failed'
} as const;

export type RunSandboxKind = typeof RunSandboxKind[keyof typeof RunSandboxKind];
