/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PairRecord } from './pair-record';
// May contain unused imports in some cases
// @ts-ignore
import type { PairTarget } from './pair-target';

export interface RunPairStatusResponse {
    'run_id': string;
    'current_pair'?: PairRecord | null;
    'targets': Array<PairTarget>;
}
