/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckRun } from './check-run';

/**
 * Pull request information for a run.
 */
export interface RunPullRequest {
    /**
     * Pull request number.
     */
    'number': number;
    /**
     * Stored GitHub pull request URL.
     */
    'html_url'?: string;
    /**
     * Lines added.
     */
    'additions'?: number;
    /**
     * Lines deleted.
     */
    'deletions'?: number;
    /**
     * Number of review comments.
     */
    'comments'?: number;
    /**
     * CI check run results.
     */
    'checks'?: Array<CheckRun>;
}

