/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Principal } from './principal';

export interface RunEventDetailResponseEvent {
    'seq': number;
    'id': string;
    'ts': string;
    'run_id': string;
    'event': string;
    'actor'?: Principal;
    'session_id'?: string;
    'node_id'?: string;
    'node_label'?: string;
    'stage_id'?: string;
    'tool_call_id'?: string;
}
