/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StageContextWindowBreakdownItem } from './stage-context-window-breakdown-item';
// May contain unused imports in some cases
// @ts-ignore
import type { StageContextWindowCountMethod } from './stage-context-window-count-method';
// May contain unused imports in some cases
// @ts-ignore
import type { StageContextWindowStaleness } from './stage-context-window-staleness';
// May contain unused imports in some cases
// @ts-ignore
import type { StageContextWindowWarning } from './stage-context-window-warning';

/**
 * Durable content-free context-window snapshot projected onto an agent stage.
 */
export interface StageContextWindowProjection {
    'provider': string;
    'model': string;
    'context_window_tokens': number;
    'input_tokens': number;
    'usage_percent': number;
    'count_method': StageContextWindowCountMethod;
    'staleness': StageContextWindowStaleness;
    'generated_at': string;
    'event_seq'?: number | null;
    'breakdown': Array<StageContextWindowBreakdownItem>;
    'warnings': Array<StageContextWindowWarning>;
}
