/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Method used to produce the context-window token total and breakdown.
 */

export const StageContextWindowCountMethod = {
    PROVIDER_API_SCALED_BREAKDOWN: 'provider_api_scaled_breakdown',
    RESPONSE_USAGE_SCALED_BREAKDOWN: 'response_usage_scaled_breakdown',
    LOCAL_ESTIMATE: 'local_estimate'
} as const;

export type StageContextWindowCountMethod = typeof StageContextWindowCountMethod[keyof typeof StageContextWindowCountMethod];
