/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Content-free warning about context-window count quality or attribution.
 */
export interface StageContextWindowWarning {
    /**
     * Stable warning code.
     */
    'code': string;
    /**
     * Human-readable warning that must not include prompt, memory, message, or tool-argument content.
     */
    'message': string;
}
