/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SystemDiskResourceScope } from './system-disk-resource-scope';

/**
 * Filesystem resources for the configured Fabro storage root.
 */
export interface SystemDiskResources {
    /**
     * Whether storage filesystem metrics are available.
     */
    'supported': boolean;
    'scope': SystemDiskResourceScope;
    /**
     * Reason metrics are unavailable when unsupported.
     */
    'unavailable_reason': string | null;
    /**
     * Configured Fabro storage directory.
     */
    'storage_path': string;
    /**
     * Mount point for the filesystem containing the storage directory.
     */
    'mount_point': string | null;
    /**
     * Filesystem name reported by the operating system.
     */
    'filesystem': string | null;
    /**
     * Total bytes on the storage filesystem.
     */
    'total_bytes': number | null;
    /**
     * Used bytes on the storage filesystem.
     */
    'used_bytes': number | null;
    /**
     * Available bytes on the storage filesystem.
     */
    'available_bytes': number | null;
    /**
     * Used percentage on the storage filesystem.
     */
    'used_percent': number | null;
    /**
     * Bytes managed by Fabro under the storage root.
     */
    'fabro_managed_bytes': number;
    /**
     * Bytes reclaimable through Fabro pruning.
     */
    'fabro_reclaimable_bytes': number;
}
