/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SystemCpuResourceScope } from './system-cpu-resource-scope';

/**
 * CPU resources visible to the Fabro server process.
 */
export interface SystemCpuResources {
    /**
     * Whether CPU metrics are available on this platform.
     */
    'supported': boolean;
    'scope': SystemCpuResourceScope;
    /**
     * Reason metrics are unavailable when unsupported.
     */
    'unavailable_reason': string | null;
    /**
     * Logical CPUs visible to the server process.
     */
    'logical_cpus': number | null;
    /**
     * CPU usage percentage, null until a delta sample is available.
     */
    'usage_percent': number | null;
    /**
     * Elapsed milliseconds since the previous CPU sample, null until a delta sample is available.
     */
    'sample_window_ms': number | null;
}
