/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to update a variable.
 */
export interface UpdateVariableRequest {
    /**
     * Replacement value. Empty values are allowed.
     */
    'value': string;
    /**
     * Optional operator-facing description. Omitted descriptions preserve the existing value.
     */
    'description'?: string;
}
