/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Non-sensitive variable available for run config interpolation.
 */
export interface Variable {
    /**
     * Env-style variable name.
     */
    'name': string;
    /**
     * Variable value.
     */
    'value': string;
    /**
     * Optional operator-facing description of the variable.
     */
    'description'?: string;
    /**
     * When the variable was first stored.
     */
    'created_at': string;
    /**
     * When the variable was last updated.
     */
    'updated_at': string;
}
