/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RelatedWorkflowDiagnostic } from './related-workflow-diagnostic';

export interface WorkflowDiagnostic {
    'rule': string;
    'severity': WorkflowDiagnosticSeverityEnum;
    'message': string;
    'node_id'?: string | null;
    'edge'?: Array<string> | null;
    'fix'?: string | null;
    'source_path'?: string | null;
    'line'?: number | null;
    'column'?: number | null;
    'span_start'?: number | null;
    'span_len'?: number | null;
    'related'?: Array<RelatedWorkflowDiagnostic>;
}

export const WorkflowDiagnosticSeverityEnum = {
    ERROR: 'error',
    WARNING: 'warning',
    INFO: 'info'
} as const;

export type WorkflowDiagnosticSeverityEnum = typeof WorkflowDiagnosticSeverityEnum[keyof typeof WorkflowDiagnosticSeverityEnum];


