_version = 1

[run.pull_request]
enabled = true
draft = false

[run.sandbox.daytona]
auto_stop_interval = 30

[run.sandbox.daytona.labels]
repo = "fabro-sh/fabro"

[run.sandbox.daytona.snapshot]
name = "fabro-v11"
cpu = 8
memory = "16GB"
disk = "20GB"
dockerfile = { path = "Dockerfile" }

# [[run.hooks]]
# id = "cargo-fmt"
# name = "cargo-fmt"
# event = "post_tool_use"
# matcher = "write_file|edit_file|apply_patch"
# script = "cargo +nightly-2026-04-14 fmt"
# blocking = true
